package com.socia.DAO;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import com.socia.DTO.AddressDTO;
import com.socia.DTO.ClientDTO;
import com.socia.DTO.ContactDTO;
import com.socia.DTO.QuotationDTO;
import com.socia.DTO.QuotationDetailDTO;

public class QuotationDAO {
	
	public ArrayList<StringBuilder> insertQuotation(QuotationDTO quotation, ArrayList<StringBuilder> queries){
		StringBuilder		sqlQuery	=	null;
		
    	sqlQuery	=	new	StringBuilder();
		sqlQuery.append(" INSERT INTO crm_quotation (crm_quotation_id, crm_address_id, crm_contact_id, ");
									 sqlQuery.append("currency, exchange_rate, crm_user_id) ");
		sqlQuery.append(" VALUES ("+quotation.getQuotationId());
		sqlQuery.append(","+quotation.getAddressId());
		sqlQuery.append(","+quotation.getContactId());
		sqlQuery.append(",'"+quotation.getCurrency()+"'");
		sqlQuery.append(","+quotation.getExchangeRate());
		sqlQuery.append(","+quotation.getUserId()+")");
		
		queries.add(sqlQuery);
    
        return queries;
    }
	
	public StringBuilder generateMail(ClientDTO client, ContactDTO contact, AddressDTO address, QuotationDTO quotation, ArrayList<QuotationDetailDTO> arrQuotationDetail){
		StringBuilder		sqlQuery	=	null;
		SimpleDateFormat	sdf			=	new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
		String				today		=	sdf.format(new Date());
		DecimalFormat		df			= 	new DecimalFormat("'$' ###,###,###.##");
		double				totalItem	= 	0;
		double				subtotal	=	0;
		double				iva			= 	0;
		double				total		=	0;
		
    	sqlQuery	=	new	StringBuilder();
    	
    	sqlQuery.append("<!DOCTYPE>");
    	  sqlQuery.append("<html>");
    		sqlQuery.append("<head>");
    			sqlQuery.append("<style type='text/css'>/* -------------------------------------INVOICE------------------------------------- */.invoice {text-align: left;width: 100%;}.invoice td {padding: 5px 0;}.invoice .invoice-items td {border-top: #eee 1px solid;}.invoice .invoice-items .total {border-top: 2px solid #333;border-bottom: 2px solid #333;font-weight: 700;}.invoice .invoice-items .subtotal {border-top: 2px solid #333;font-weight: 700;}.invoice .invoice-items .iva {border-top: 2px solid #333;font-weight: 700;}.invoice .invoice-items .no-border{border-bottom: none;border-top: none;}.invoice .invoice-items .header td {border-top: 2px solid #333;border-bottom: 2px solid #333;font-weight: 700;}/* -------------------------------------OTHER STYLES THAT MIGHT BE USEFUL------------------------------------- */.aligncenter {text-align: center;}.alignright {text-align: right;}.alignleft {text-align: left;}/* CLIENT-SPECIFIC STYLES */table, td, a{-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;} /* Prevent WebKit and Windows mobile changing default text sizes */table, td{mso-table-lspace: 0pt; mso-table-rspace: 0pt;} /* Remove spacing between tables in Outlook 2007 and up */img{-ms-interpolation-mode: bicubic;} /* Allow smoother rendering of resized image in Internet Explorer *//* RESET STYLES */img{border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;}table{border-collapse: collapse !important;}body{height: 100% !important; margin: 0 !important; padding: 0 !important; width: 100% !important;}/* iOS BLUE LINKS */a[x-apple-data-detectors] {color: inherit !important;text-decoration: none !important;font-size: inherit !important;font-family: inherit !important;font-weight: inherit !important;line-height: inherit !important;}/* MOBILE STYLES */@media screen and (max-width: 525px) {/* ALLOWS FOR FLUID TABLES */.wrapper {width: 100% !important;max-width: 100% !important;}/* ADJUSTS LAYOUT OF LOGO IMAGE */.logo img {margin: 0 auto !important;}/* USE THESE CLASSES TO HIDE CONTENT ON MOBILE */.mobile-hide {display: none !important;}.img-max {max-width: 100% !important;width: 100% !important;height: auto !important;}/* FULL-WIDTH TABLES */.responsive-table {width: 100% !important;}/* UTILITY CLASSES FOR ADJUSTING PADDING ON MOBILE */.padding {padding: 10px 5% 15px 5% !important;}.padding-meta {padding: 30px 5% 0px 5% !important;text-align: center;}.padding-copy {padding: 10px 5% 10px 5% !important;text-align: center;}.no-padding {padding: 0 !important;}.section-padding {padding: 50px 15px 50px 15px !important;}/* ADJUST BUTTONS ON MOBILE */.mobile-button-container {margin: 0 auto;width: 100% !important;}.mobile-button {padding: 15px !important;border: 0 !important;font-size: 16px !important;display: block !important;}}/* ANDROID CENTER FIX */div[style*='margin: 16px 0;'] { margin: 0 !important; }</style>");
    		sqlQuery.append("</head>");
    		sqlQuery.append("<body>");
    		 	sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%'>");
		 			sqlQuery.append("<tr>");
		 				sqlQuery.append("<td bgcolor='#ffffff' align='center'>");
		 					sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
		 					sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
		 					sqlQuery.append("<tr>");
		 					sqlQuery.append("<td align='center' valign='top' width='800'>");
		 					sqlQuery.append("<![endif]-->");
		 						sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='wrapper'>");
		 							sqlQuery.append("<tr>");
    		 							sqlQuery.append("<td valign='top' style='padding: 15px 0;' class='logo'>");
    		 								sqlQuery.append("<a href='http://gruposocia.com' target='_blank'>");
    		 									sqlQuery.append("<img alt='Logo' src='images/logo.jpg' width='250' height='60' style='display: block; font-family: Helvetica, Arial, sans-serif; color: #ffffff; font-size: 16px;' border='0'>");
    		 								sqlQuery.append("</a>");
    		 							sqlQuery.append("</td>");
    		 							sqlQuery.append("<td align='right'>");
		 									sqlQuery.append("<p style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>Referencia: </p>");
		 									sqlQuery.append("<p style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+today+"</p>");
					                    sqlQuery.append("</td>");
					                sqlQuery.append("</tr>");
					            sqlQuery.append("</table>");
				            sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
				            sqlQuery.append("</td>");
				       		sqlQuery.append("</tr>");
				       		sqlQuery.append("</table>");
				       		sqlQuery.append("<![endif]-->");
						sqlQuery.append("</td>");
					sqlQuery.append("</tr>");
					sqlQuery.append("<tr>");
						sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;'>");
							sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
							sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
							sqlQuery.append("<tr>");
							sqlQuery.append("<td align='center' valign='top' width='800'>");
							sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 100%;' class='responsive-table'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Raz&oacute;n Social</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyName'>"+client.getCompanyName()+"</c:out></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Contacto</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getFirstName()+" "+contact.getLastName()+" </td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Direcci&oacute;n</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyAddress'>"+address.getStreet()+" "+address.getExtNum()+" Int. "+address.getIntNum()+", "+address.getSuburb()+", "+address.getCity()+", "+address.getState()+", "+address.getCountry()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																sqlQuery.append("<!-- LEFT COLUMN -->");
																sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																			sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Tel&eacute;fono</b></td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("</td>");
																	sqlQuery.append("</tr>");
																sqlQuery.append("</table>");
																sqlQuery.append("<!-- RIGHT COLUMN -->");
																sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																			sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getPhone()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td style='border-bottom: border-top: 1px solid #eaeaea;'>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>email</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getEmail()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
											sqlQuery.append("</table>");
										sqlQuery.append("</td>");
										sqlQuery.append("<td width='10%' style='max-width: 10%;'></td>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 100%;' class='responsive-table'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Proveedor</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyName'>SOLUCIONES DE IMPRESIÓN ADMINISTRADA, S.A. DE C.V.</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Direcci&oacute;n</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																					sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																						sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																							sqlQuery.append("<tr>");
																								sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyAddress'> Medellín 81, int. 302, Col. Roma Norte</td>");
																							sqlQuery.append("</tr>");
																						sqlQuery.append("</table>");
																					sqlQuery.append("</td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("</td>");
																	sqlQuery.append("</tr>");
																sqlQuery.append("</table>");
															sqlQuery.append("</td>");
														sqlQuery.append("</tr>");
														sqlQuery.append("<tr>");
															sqlQuery.append("<td>");
																sqlQuery.append("<!-- TWO COLUMNS -->");
																	sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																				sqlQuery.append("<!-- LEFT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																							sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																								sqlQuery.append("<tr>");
																									sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'></td>");
																								sqlQuery.append("</tr>");
																							sqlQuery.append("</table>");
																						sqlQuery.append("</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																				sqlQuery.append("<!-- RIGHT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																							sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																								sqlQuery.append("<tr>");
																									sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>Del. Cuauhtémoc, DF, C.P.06700</td>");
																								sqlQuery.append("</tr>");
																							sqlQuery.append("</table>");
																						sqlQuery.append("</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td>");
																	sqlQuery.append("<!-- TWO COLUMNS -->");
																	sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																				sqlQuery.append("<!-- LEFT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																						sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																							sqlQuery.append("<tr>");
																								sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Contacto</b></td>");
																							sqlQuery.append("</tr>");
																						sqlQuery.append("</table>");
																					sqlQuery.append("</td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("<!-- RIGHT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>EMMA CRISTINA LÓPEZ MEDINA </td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																	sqlQuery.append("</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
													sqlQuery.append("<tr>");
														sqlQuery.append("<td style='border-bottom: border-top: 1px solid #eaeaea;'>");
															sqlQuery.append("<!-- TWO COLUMNS -->");
															sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																		sqlQuery.append("<!-- LEFT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>email</b></td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																		sqlQuery.append("<!-- RIGHT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>elopez@socia.com.mx</td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																	sqlQuery.append("</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
												sqlQuery.append("</table>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;' class='padding'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table class='invoice'  cellspacing='0' cellpadding='0' border='0' width='100%'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<table class='invoice-items' cellpadding='0' cellspacing='0' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>");
															sqlQuery.append("<tr  class='header aligncenter' style='font-weight:bold;'>");
																sqlQuery.append("<td>Cantidad</td>");
																	sqlQuery.append("<td>Producto</td>");
																	sqlQuery.append("<td>Descripción</td>");
																	sqlQuery.append("<td>Tiempo de entrega</td>");
																	sqlQuery.append("<td>Precio unitario</td>");
																	sqlQuery.append("<td>Subtotal</td>");
																sqlQuery.append("</tr>");
		
																
																for(int index=0; index < arrQuotationDetail.size(); index++){
																	totalItem = arrQuotationDetail.get(index).getUnitPrice() * arrQuotationDetail.get(index).getQuantity();
																	subtotal += totalItem;
																	
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getQuantity()+"</td>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getItemId()+"</td>");
																		sqlQuery.append("<td></td>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getEstimatedShipping()+"</td>");
																		sqlQuery.append("<td class='alignright'>"+df.format(arrQuotationDetail.get(index).getUnitPrice())+"</td>");
																		sqlQuery.append("<td class='alignright'>"+df.format(totalItem)+"</td>");
																	sqlQuery.append("</tr>");
																}
																
																
																iva = subtotal * 0.16;
																total = subtotal + iva;
																
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'>Subtotal</td>");
																	sqlQuery.append("<td class='subtotal alignright'>"+df.format(subtotal)+"</td>");
																sqlQuery.append("</tr>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='iva'>IVA</td>");
																	sqlQuery.append("<td class='iva alignright'>"+df.format(iva)+"</td>");
																sqlQuery.append("</tr>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='no-border'><b>Moneda:</b></td>");
																	sqlQuery.append("<td class='no-border'><c:out value='${ sessionScope.quotation.currency }'></c:out></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='total'>Total</td>");
																	sqlQuery.append("<td class='total alignright'>"+df.format(total)+"</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
												sqlQuery.append("</table>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- COPY -->");
														sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td align='left' style='padding: 0 0 0 0; font-size: 14px; line-height: 18px; font-family: Helvetica, Arial, sans-serif; color: #f51616; font-weight:bold; font-style: italic;' class='padding-copy'>LOS PRECIOS SON SUJETOS A CAMBIOS SIN PREVIO AVISO.</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
											sqlQuery.append("</table>");
										sqlQuery.append("</td>");
									sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 20px 0px;'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<!-- UNSUBSCRIBE COPY -->");
									sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center' style='max-width: 800px;' class='responsive-table'>");
										sqlQuery.append("<tr>");
											sqlQuery.append("<td align='center' style='font-size: 12px; line-height: 18px; font-family: Helvetica, Arial, sans-serif; color:#666666;'>");
												sqlQuery.append("Medellín 81 302, Roma Norte, Cuauhtémoc, D.F.");
												sqlQuery.append("<br>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
					sqlQuery.append("</table>");
    		sqlQuery.append("</body>");
    	  sqlQuery.append("</html>");
    	
    	return sqlQuery;
	}
	
}
