package com.socia.DAO;

import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import com.socia.DTO.AddressDTO;
import com.socia.DTO.ClientDTO;
import com.socia.DTO.ContactDTO;
import com.socia.DTO.QuotationDTO;
import com.socia.DTO.QuotationDetailDTO;
import com.socia.DTO.QuotationLogDTO;
import com.socia.DTO.TenderLogDTO;
import com.socia.conexion.Conexion;

public class QuotationDAO {
	
	public ArrayList<StringBuilder> insertQuotation(QuotationDTO quotation, ArrayList<StringBuilder> queries){
		StringBuilder		sqlQuery	=	null;
		
    	sqlQuery	=	new	StringBuilder();
		sqlQuery.append(" INSERT INTO crm_quotation (crm_quotation_id, crm_address_id, crm_client_id, ");
									 sqlQuery.append("currency, exchange_rate, crm_user_id, closing_date, date_created) ");
		sqlQuery.append(" VALUES ("+quotation.getQuotationId());
		sqlQuery.append(","+quotation.getAddressId());
		sqlQuery.append(","+quotation.getClientId());
		sqlQuery.append(",'"+quotation.getCurrency()+"'");
		sqlQuery.append(","+quotation.getExchangeRate());
		sqlQuery.append(","+quotation.getUserId());
		sqlQuery.append(",'"+quotation.getClosingDate()+"'");
		sqlQuery.append(", now())");
		
		System.out.println(quotation.toString());
		
		queries.add(sqlQuery);
    
        return queries;
    }
	
	public void generateExcelFile(ClientDTO client, ContactDTO contact, AddressDTO address, QuotationDTO quotation, ArrayList<QuotationDetailDTO> arrQuotationDetail){
		HSSFWorkbook workbook = new HSSFWorkbook();
		HSSFSheet sheet = workbook.createSheet("Cotización");
		
		SimpleDateFormat	sdf			=	new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
		String				today		=	sdf.format(new Date());
		DecimalFormat		df			= 	new DecimalFormat("'$' ###,###,###.##");
		double				totalItem	= 	0;
		double				subtotal	= 	0;
		double				iva			= 	0;
		double				total		= 	0;
		
		int rownum = 0;
		int cellnum = 0;
		Row row = sheet.createRow(rownum++);
		Cell cell = row.createCell(cellnum++);
		cell.setCellValue(today);
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("Razón Social");
		cell = row.createCell(cellnum++);
		cell.setCellValue(client.getCompanyName());
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Proveedor");
		cell = row.createCell(cellnum++);
		cell.setCellValue("SOLUCIONES DE IMPRESIÓN ADMINISTRADA, S.A. DE C.V.");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("Contacto");
		cell = row.createCell(cellnum++);
		cell.setCellValue(contact.getFirstName()+" "+contact.getLastName());
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Dirección");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Medellín 81, int. 302, Col. Roma Norte");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("Dirección");
		cell = row.createCell(cellnum++);
		cell.setCellValue(address.getStreet()+" "+address.getExtNum()+" Int. "+address.getIntNum()+", "+address.getSuburb()+", "+address.getCity()+", "+address.getState()+", "+address.getCountry());
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Del. Cuauhtémoc, DF, C.P.06700");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("Teléfono");
		cell = row.createCell(cellnum++);
		cell.setCellValue(contact.getPhone());
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Contacto");
		cell = row.createCell(cellnum++);
		cell.setCellValue("EMMA CRISTINA LÓPEZ MEDINA");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("email");
		cell = row.createCell(cellnum++);
		cell.setCellValue(contact.getEmail());
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("email");
		cell = row.createCell(cellnum++);
		cell.setCellValue("elopez@socia.com.mx");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");

		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("Cantidad");
		cell = row.createCell(cellnum++);
		cell.setCellValue("SKU / No. Parte");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Descripción");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Tiempo de entrega");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Precio Unitario");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Subtotal");
		
		for(int index=0; index < arrQuotationDetail.size(); index++){
			totalItem = arrQuotationDetail.get(index).getUnitPrice() * arrQuotationDetail.get(index).getQuantity();
			subtotal += totalItem;
			cellnum = 0;
			row = sheet.createRow(rownum++);
			cell = row.createCell(cellnum++);
			cell.setCellValue(arrQuotationDetail.get(index).getQuantity());
			cell = row.createCell(cellnum++);
			cell.setCellValue(arrQuotationDetail.get(index).getItemId());
			cell = row.createCell(cellnum++);
			cell.setCellValue(arrQuotationDetail.get(index).getDescription());
			cell = row.createCell(cellnum++);
			cell.setCellValue(arrQuotationDetail.get(index).getEstimatedShipping());
			cell = row.createCell(cellnum++);
			cell.setCellValue(df.format(arrQuotationDetail.get(index).getUnitPrice()));
			cell = row.createCell(cellnum++);
			cell.setCellValue(df.format(totalItem));
		}
		
		iva = subtotal * 0.16;
		total = subtotal + iva;

		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Subtotal");
		cell = row.createCell(cellnum++);
		cell.setCellValue(subtotal);
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("IVA");
		cell = row.createCell(cellnum++);
		cell.setCellValue(iva);
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("");
		cell = row.createCell(cellnum++);
		cell.setCellValue("Total");
		cell = row.createCell(cellnum++);
		cell.setCellValue(total);
		
		cellnum = 0;
		row = sheet.createRow(rownum++);
		cell = row.createCell(cellnum++);
		cell.setCellValue("LOS PRECIOS SON SUJETOS A CAMBIOS SIN PREVIO AVISO");
		
		try {
			FileOutputStream out = 
					new FileOutputStream(new File("cotizacion.xls"));
			workbook.write(out);
			out.close();
			System.out.println("Excel written successfully..");
			
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public StringBuilder generateMail(ClientDTO client, ContactDTO contact, AddressDTO address, QuotationDTO quotation, ArrayList<QuotationDetailDTO> arrQuotationDetail){
		StringBuilder		sqlQuery	=	null;
		SimpleDateFormat	sdf			=	new SimpleDateFormat("dd 'de' MMMM 'de' yyyy");
		String				today		=	sdf.format(new Date());
		DecimalFormat		df			= 	new DecimalFormat("'$' ###,###,###.##");
		double				totalItem	= 	0;
		double				subtotal	=	0;
		double				iva			= 	0;
		double				total		=	0;
		
    	sqlQuery	=	new	StringBuilder();
    	
    	sqlQuery.append("<!DOCTYPE>");
    	  sqlQuery.append("<html>");
    		sqlQuery.append("<head>");
    			sqlQuery.append("<style type='text/css'>/* -------------------------------------INVOICE------------------------------------- */.invoice {text-align: left;width: 100%;}.invoice td {padding: 5px 0;}.invoice .invoice-items td {border-top: #eee 1px solid;}.invoice .invoice-items .total {border-top: 2px solid #333;border-bottom: 2px solid #333;font-weight: 700;}.invoice .invoice-items .subtotal {border-top: 2px solid #333;font-weight: 700;}.invoice .invoice-items .iva {border-top: 2px solid #333;font-weight: 700;}.invoice .invoice-items .no-border{border-bottom: none;border-top: none;}.invoice .invoice-items .header td {border-top: 2px solid #333;border-bottom: 2px solid #333;font-weight: 700;}/* -------------------------------------OTHER STYLES THAT MIGHT BE USEFUL------------------------------------- */.aligncenter {text-align: center;}.alignright {text-align: right;}.alignleft {text-align: left;}/* CLIENT-SPECIFIC STYLES */table, td, a{-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;} /* Prevent WebKit and Windows mobile changing default text sizes */table, td{mso-table-lspace: 0pt; mso-table-rspace: 0pt;} /* Remove spacing between tables in Outlook 2007 and up */img{-ms-interpolation-mode: bicubic;} /* Allow smoother rendering of resized image in Internet Explorer *//* RESET STYLES */img{border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;}table{border-collapse: collapse !important;}body{height: 100% !important; margin: 0 !important; padding: 0 !important; width: 100% !important;}/* iOS BLUE LINKS */a[x-apple-data-detectors] {color: inherit !important;text-decoration: none !important;font-size: inherit !important;font-family: inherit !important;font-weight: inherit !important;line-height: inherit !important;}/* MOBILE STYLES */@media screen and (max-width: 525px) {/* ALLOWS FOR FLUID TABLES */.wrapper {width: 100% !important;max-width: 100% !important;}/* ADJUSTS LAYOUT OF LOGO IMAGE */.logo img {margin: 0 auto !important;}/* USE THESE CLASSES TO HIDE CONTENT ON MOBILE */.mobile-hide {display: none !important;}.img-max {max-width: 100% !important;width: 100% !important;height: auto !important;}/* FULL-WIDTH TABLES */.responsive-table {width: 100% !important;}/* UTILITY CLASSES FOR ADJUSTING PADDING ON MOBILE */.padding {padding: 10px 5% 15px 5% !important;}.padding-meta {padding: 30px 5% 0px 5% !important;text-align: center;}.padding-copy {padding: 10px 5% 10px 5% !important;text-align: center;}.no-padding {padding: 0 !important;}.section-padding {padding: 50px 15px 50px 15px !important;}/* ADJUST BUTTONS ON MOBILE */.mobile-button-container {margin: 0 auto;width: 100% !important;}.mobile-button {padding: 15px !important;border: 0 !important;font-size: 16px !important;display: block !important;}}/* ANDROID CENTER FIX */div[style*='margin: 16px 0;'] { margin: 0 !important; }</style>");
    		sqlQuery.append("</head>");
    		sqlQuery.append("<body>");
    		 	sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%'>");
		 			sqlQuery.append("<tr>");
		 				sqlQuery.append("<td bgcolor='#ffffff' align='center'>");
		 					sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
		 					sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
		 					sqlQuery.append("<tr>");
		 					sqlQuery.append("<td align='center' valign='top' width='800'>");
		 					sqlQuery.append("<![endif]-->");
		 						sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='wrapper'>");
		 							sqlQuery.append("<tr>");
    		 							sqlQuery.append("<td valign='top' style='padding: 15px 0;' class='logo'>");
    		 								sqlQuery.append("<a href='http://gruposocia.com' target='_blank'>");
    		 									sqlQuery.append("<img alt='Logo' src='http://gruposocia.com/wp-content/uploads/2016/06/grupo-socia-logo-jp-hz-01-1.png' width='250' height='60' style='display: block; font-family: Helvetica, Arial, sans-serif; color: #ffffff; font-size: 16px;' border='0'>");
    		 								sqlQuery.append("</a>");
    		 							sqlQuery.append("</td>");
    		 							sqlQuery.append("<td align='right'>");
		 									sqlQuery.append("<p style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>Referencia: </p>");
		 									sqlQuery.append("<p style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+today+"</p>");
					                    sqlQuery.append("</td>");
					                sqlQuery.append("</tr>");
					            sqlQuery.append("</table>");
				            sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
				            sqlQuery.append("</td>");
				       		sqlQuery.append("</tr>");
				       		sqlQuery.append("</table>");
				       		sqlQuery.append("<![endif]-->");
						sqlQuery.append("</td>");
					sqlQuery.append("</tr>");
					sqlQuery.append("<tr>");
						sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;'>");
							sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
							sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
							sqlQuery.append("<tr>");
							sqlQuery.append("<td align='center' valign='top' width='800'>");
							sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 100%;' class='responsive-table'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Raz&oacute;n Social</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyName'>"+client.getCompanyName()+"</c:out></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Contacto</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getFirstName()+" "+contact.getLastName()+" </td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Direcci&oacute;n</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyAddress'>"+address.getStreet()+" "+address.getExtNum()+" Int. "+address.getIntNum()+", "+address.getSuburb()+", "+address.getCity()+", "+address.getState()+", "+address.getCountry()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																sqlQuery.append("<!-- LEFT COLUMN -->");
																sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																			sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Tel&eacute;fono</b></td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("</td>");
																	sqlQuery.append("</tr>");
																sqlQuery.append("</table>");
																sqlQuery.append("<!-- RIGHT COLUMN -->");
																sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																			sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getPhone()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td style='border-bottom: border-top: 1px solid #eaeaea;'>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='37%' style='width: 37%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>email</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='57%' style='width: 57%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>"+contact.getEmail()+"</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
											sqlQuery.append("</table>");
										sqlQuery.append("</td>");
										sqlQuery.append("<td width='10%' style='max-width: 10%;'></td>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 100%;' class='responsive-table'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Proveedor</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyName'>SOLUCIONES DE IMPRESIÓN ADMINISTRADA, S.A. DE C.V.</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- TWO COLUMNS -->");
														sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																	sqlQuery.append("<!-- LEFT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Direcci&oacute;n</b></td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																	sqlQuery.append("<!-- RIGHT COLUMN -->");
																	sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																					sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																						sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																							sqlQuery.append("<tr>");
																								sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;' id='previewCompanyAddress'> Medellín 81, int. 302, Col. Roma Norte</td>");
																							sqlQuery.append("</tr>");
																						sqlQuery.append("</table>");
																					sqlQuery.append("</td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("</td>");
																	sqlQuery.append("</tr>");
																sqlQuery.append("</table>");
															sqlQuery.append("</td>");
														sqlQuery.append("</tr>");
														sqlQuery.append("<tr>");
															sqlQuery.append("<td>");
																sqlQuery.append("<!-- TWO COLUMNS -->");
																	sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																				sqlQuery.append("<!-- LEFT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																							sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																								sqlQuery.append("<tr>");
																									sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'></td>");
																								sqlQuery.append("</tr>");
																							sqlQuery.append("</table>");
																						sqlQuery.append("</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																				sqlQuery.append("<!-- RIGHT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																					sqlQuery.append("<tr>");
																						sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																							sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																								sqlQuery.append("<tr>");
																									sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>Del. Cuauhtémoc, DF, C.P.06700</td>");
																								sqlQuery.append("</tr>");
																							sqlQuery.append("</table>");
																						sqlQuery.append("</td>");
																					sqlQuery.append("</tr>");
																				sqlQuery.append("</table>");
																			sqlQuery.append("</td>");
																		sqlQuery.append("</tr>");
																	sqlQuery.append("</table>");
																sqlQuery.append("</td>");
															sqlQuery.append("</tr>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td>");
																	sqlQuery.append("<!-- TWO COLUMNS -->");
																	sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																		sqlQuery.append("<tr>");
																			sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																				sqlQuery.append("<!-- LEFT COLUMN -->");
																				sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																				sqlQuery.append("<tr>");
																					sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																						sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																							sqlQuery.append("<tr>");
																								sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>Contacto</b></td>");
																							sqlQuery.append("</tr>");
																						sqlQuery.append("</table>");
																					sqlQuery.append("</td>");
																				sqlQuery.append("</tr>");
																			sqlQuery.append("</table>");
																		sqlQuery.append("<!-- RIGHT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>EMMA CRISTINA LÓPEZ MEDINA </td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																	sqlQuery.append("</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
													sqlQuery.append("<tr>");
														sqlQuery.append("<td style='border-bottom: border-top: 1px solid #eaeaea;'>");
															sqlQuery.append("<!-- TWO COLUMNS -->");
															sqlQuery.append("<table cellspacing='0' cellpadding='0' border='0' width='100%'>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td valign='top' style='padding: 0;' class='mobile-wrapper'>");
																		sqlQuery.append("<!-- LEFT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='27%' style='width: 27%;' align='left'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'><b>email</b></td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																		sqlQuery.append("<!-- RIGHT COLUMN -->");
																		sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='67%' style='width: 67%;' align='right'>");
																			sqlQuery.append("<tr>");
																				sqlQuery.append("<td style='padding: 0 0 10px 0;'>");
																					sqlQuery.append("<table cellpadding='0' cellspacing='0' border='0' width='100%'>");
																						sqlQuery.append("<tr>");
																							sqlQuery.append("<td align='left' style='font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>elopez@socia.com.mx</td>");
																						sqlQuery.append("</tr>");
																					sqlQuery.append("</table>");
																				sqlQuery.append("</td>");
																			sqlQuery.append("</tr>");
																		sqlQuery.append("</table>");
																	sqlQuery.append("</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
												sqlQuery.append("</table>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;' class='padding'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table class='invoice'  cellspacing='0' cellpadding='0' border='0' width='100%'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<table class='invoice-items' cellpadding='0' cellspacing='0' style='width:100%;font-family: Arial, sans-serif; color: #333333; font-size: 12px;'>");
															sqlQuery.append("<tr  class='header aligncenter' style='font-weight:bold;'>");
																sqlQuery.append("<td>Cantidad</td>");
																	sqlQuery.append("<td>SKU / No. Parte</td>");
																	sqlQuery.append("<td>Descripción</td>");
																	sqlQuery.append("<td>Tiempo de entrega</td>");
																	sqlQuery.append("<td>Precio unitario</td>");
																	sqlQuery.append("<td>Subtotal</td>");
																sqlQuery.append("</tr>");
		
																
																for(int index=0; index < arrQuotationDetail.size(); index++){
																	totalItem = arrQuotationDetail.get(index).getUnitPrice() * arrQuotationDetail.get(index).getQuantity();
																	subtotal += totalItem;
																	
																	sqlQuery.append("<tr>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getQuantity()+"</td>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getItemId()+"</td>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getDescription()+"</td>");
																		sqlQuery.append("<td>"+arrQuotationDetail.get(index).getEstimatedShipping()+"</td>");
																		sqlQuery.append("<td class='alignright'>"+df.format(arrQuotationDetail.get(index).getUnitPrice())+"</td>");
																		sqlQuery.append("<td class='alignright'>"+df.format(totalItem)+"</td>");
																	sqlQuery.append("</tr>");
																}
																
																
																iva = subtotal * 0.16;
																total = subtotal + iva;
																
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'></td>");
																	sqlQuery.append("<td class='subtotal'>Subtotal</td>");
																	sqlQuery.append("<td class='subtotal alignright'>"+df.format(subtotal)+"</td>");
																sqlQuery.append("</tr>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='iva'>IVA</td>");
																	sqlQuery.append("<td class='iva alignright'>"+df.format(iva)+"</td>");
																sqlQuery.append("</tr>");
																sqlQuery.append("<tr>");
																	sqlQuery.append("<td class='no-border'><b>Moneda:</b></td>");
																	sqlQuery.append("<td class='no-border'>"+quotation.getCurrency()+"</td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='no-border'></td>");
																	sqlQuery.append("<td class='total'>Total</td>");
																	sqlQuery.append("<td class='total alignright'>"+df.format(total)+"</td>");
																sqlQuery.append("</tr>");
															sqlQuery.append("</table>");
														sqlQuery.append("</td>");
													sqlQuery.append("</tr>");
												sqlQuery.append("</table>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 15px;'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<table border='0' cellpadding='0' cellspacing='0' width='100%' style='max-width: 800px;' class='responsive-table'>");
									sqlQuery.append("<tr>");
										sqlQuery.append("<td>");
											sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
												sqlQuery.append("<tr>");
													sqlQuery.append("<td>");
														sqlQuery.append("<!-- COPY -->");
														sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
															sqlQuery.append("<tr>");
																sqlQuery.append("<td align='left' style='padding: 0 0 0 0; font-size: 14px; line-height: 18px; font-family: Helvetica, Arial, sans-serif; color: #f51616; font-weight:bold; font-style: italic;' class='padding-copy'>LOS PRECIOS SON SUJETOS A CAMBIOS SIN PREVIO AVISO.</td>");
															sqlQuery.append("</tr>");
														sqlQuery.append("</table>");
													sqlQuery.append("</td>");
												sqlQuery.append("</tr>");
											sqlQuery.append("</table>");
										sqlQuery.append("</td>");
									sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
						sqlQuery.append("<tr>");
							sqlQuery.append("<td bgcolor='#ffffff' align='center' style='padding: 20px 0px;'>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("<table align='center' border='0' cellspacing='0' cellpadding='0' width='800'>");
								sqlQuery.append("<tr>");
								sqlQuery.append("<td align='center' valign='top' width='800'>");
								sqlQuery.append("<![endif]-->");
								sqlQuery.append("<!-- UNSUBSCRIBE COPY -->");
									sqlQuery.append("<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center' style='max-width: 800px;' class='responsive-table'>");
										sqlQuery.append("<tr>");
											sqlQuery.append("<td align='center' style='font-size: 12px; line-height: 18px; font-family: Helvetica, Arial, sans-serif; color:#666666;'>");
												sqlQuery.append("Medellín 81 302, Roma Norte, Cuauhtémoc, D.F.");
												sqlQuery.append("<br>");
											sqlQuery.append("</td>");
										sqlQuery.append("</tr>");
									sqlQuery.append("</table>");
								sqlQuery.append("<!--[if (gte mso 9)|(IE)]>");
								sqlQuery.append("</td>");
								sqlQuery.append("</tr>");
								sqlQuery.append("</table>");
								sqlQuery.append("<![endif]-->");
							sqlQuery.append("</td>");
						sqlQuery.append("</tr>");
					sqlQuery.append("</table>");
    		sqlQuery.append("</body>");
    	  sqlQuery.append("</html>");
    	
    	return sqlQuery;
	}
	
	public ArrayList<QuotationLogDTO> getQuotationLog(String fechaIni,String fechaFin,int userId){
		Conexion			sociaDB		=	null;
		Connection			connection	=	null;
		PreparedStatement	statement	=	null;
		ResultSet			resultSet	=	null;
		StringBuilder		sqlQuery	=	null;
		
		/** Quotation objects*/
		int							quotationId		= 0;
		String			 			companyName		= "";
		String					 	itemId			= "";
		int		 					quantity		= 0;
		double						unitPrice		= 0;
		String						currency		= "";
		double						margin			= 0;
		Date						deadline		= null;
		Date						date			= null;
		QuotationLogDTO				quotation		= null;
		ArrayList<QuotationLogDTO>	arrQuotation	=  new ArrayList<QuotationLogDTO>();
		
		try{
			sqlQuery	=	new	StringBuilder();
			sqlQuery.append(" SELECT q.crm_quotation_id, cli.company_name, qd.crm_item_id, qd.quantity, qd.unit_price, ");
			sqlQuery.append(" q.currency, qd.margin, q.date_created ");
			sqlQuery.append(" FROM crm_quotation_detail qd ");
			sqlQuery.append(" JOIN crm_quotation q ON qd.crm_quotation_id = q.crm_quotation_id ");
			sqlQuery.append(" JOIN crm_client cli ON cli.crm_client_id = q.crm_client_id ");
			sqlQuery.append(" WHERE DATE(q.date_created) >= ? ");
			sqlQuery.append(" AND DATE(q.date_created) <= ? ");
			sqlQuery.append(" AND q.crm_user_id = ? ");
			sqlQuery.append(" ORDER BY q.date_created ");
			
			sociaDB		=	new	Conexion();
			connection	=	sociaDB.getConnection1();
			statement	=	connection.prepareStatement(sqlQuery.toString());
			
			statement.setString(1, fechaIni);
			statement.setString(2, fechaFin);
			statement.setInt(3, userId);
			
			resultSet	=	statement.executeQuery();
			
			while(resultSet.next()){
				quotationId = resultSet.getInt(1);
				companyName=resultSet.getString(2);
				itemId = resultSet.getString(3);
				quantity = resultSet.getInt(4);
				unitPrice = resultSet.getDouble(5);
				currency = resultSet.getString(6);
				margin = resultSet.getDouble(7);
				date = resultSet.getDate(8);
				
				quotation = new QuotationLogDTO(quotationId, date, companyName, itemId, quantity, unitPrice, currency, margin, deadline);
				
				arrQuotation.add(quotation);
			}
			
		}catch(Exception exception){
			exception.printStackTrace();
		}finally{
			try{
				resultSet.close();
				statement.close();
				connection.close();
			}catch(Exception closeException){
				closeException.printStackTrace();
			}
		}
		
		return arrQuotation;
	}
	
}
