-- MySQL Script generated by MySQL Workbench
-- 10/04/16 21:08:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema socia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `socia` ;

-- -----------------------------------------------------
-- Schema socia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socia` DEFAULT CHARACTER SET utf8 ;
USE `socia` ;

-- -----------------------------------------------------
-- Table `socia`.`crm_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_user` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_user` (
  `crm_user_id` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dateCreated` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_user_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `crm_user`
--

LOCK TABLES `crm_user` WRITE;
/*!40000 ALTER TABLE `crm_user` DISABLE KEYS */;
INSERT INTO `crm_user` VALUES (1,'admin','1234','Administrador','Socia','admin@socia.com.mx','2016-10-04 00:00:00',NULL),(2,'ejecutivo','1234','Ejecutivo','Socia','ejecutivo@socia.com.mx','2016-10-04 00:00:00',NULL);
/*!40000 ALTER TABLE `crm_user` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_user_role` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_user_role` (
  `crm_user_role_id` INT NOT NULL,
  `roleDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_user_role_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `crm_user_role`
--

LOCK TABLES `crm_user_role` WRITE;
/*!40000 ALTER TABLE `crm_user_role` DISABLE KEYS */;
INSERT INTO `crm_user_role` VALUES (1,'BDM'),(2,'Ejecutivo');
/*!40000 ALTER TABLE `crm_user_role` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_client` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_client` (
  `crm_client_id` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `crm_bdm_id` INT NOT NULL,
  PRIMARY KEY (`crm_client_id`),
  INDEX `fk_crm_client_crm_users1_idx` (`crm_bdm_id` ASC),
  CONSTRAINT `fk_crm_client_crm_users1`
    FOREIGN KEY (`crm_bdm_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `crm_client`
--

LOCK TABLES `crm_client` WRITE;
/*!40000 ALTER TABLE `crm_client` DISABLE KEYS */;
INSERT INTO `crm_client` VALUES (1,'PRUEBA SA de CV','A',1);
/*!40000 ALTER TABLE `crm_client` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_contact` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_contact` (
  `crm_contact_id` INT NOT NULL,
  `contact_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_contact_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `crm_contact`
--

LOCK TABLES `crm_contact` WRITE;
/*!40000 ALTER TABLE `crm_contact` DISABLE KEYS */;
INSERT INTO `crm_contact` VALUES (1,'Ana Bobana','12345678','ana@company.com','A'),(2,'Pepe Pecas','87654321','pepe@company.com','A');
/*!40000 ALTER TABLE `crm_contact` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_call` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_call` (
  `crm_call_id` INT NOT NULL,
  `comments` VARCHAR(255) NULL,
  `crm_client_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  PRIMARY KEY (`crm_call_id`),
  INDEX `fk_crm_call_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_call_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_call_crm_contact1_idx` (`crm_contact_id` ASC),
  CONSTRAINT `fk_crm_call_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_call_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_call_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `socia`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_client_consecutives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_client_consecutives` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_client_consecutives` (
  `crm_client_id` INT NOT NULL,
  `table` VARCHAR(45) NULL,
  `consecutive` INT NULL,
  PRIMARY KEY (`crm_client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_appointment` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_appointment` (
  `crm_appointment_id` INT NOT NULL,
  `date` DATETIME NULL,
  `crm_client_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  `crm_bdm_id` INT NOT NULL,
  PRIMARY KEY (`crm_appointment_id`),
  INDEX `fk_crm_appointments_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_appointments_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_appointments_crm_contact1_idx` (`crm_contact_id` ASC),
  INDEX `fk_crm_appointment_crm_user1_idx` (`crm_bdm_id` ASC),
  CONSTRAINT `fk_crm_appointments_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointments_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointments_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `socia`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointment_crm_user1`
    FOREIGN KEY (`crm_bdm_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_address` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_address` (
  `crm_address_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `ext_num` VARCHAR(45) NULL,
  `int_num` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_address_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `crm_address`
--

LOCK TABLES `crm_address` WRITE;
/*!40000 ALTER TABLE `crm_address` DISABLE KEYS */;
INSERT INTO `crm_address` VALUES (1,'Calle 21','101','102','Benito Juarez','Ciudad de México','México',3800,'A'),(2,'Calle 23','103','104','Benito Juarez','Ciudad de México','México',3800,'A');
/*!40000 ALTER TABLE `crm_address` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_brand` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_brand` (
  `crm_brand_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_business_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_business_line` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_business_line` (
  `crm_business_line_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_business_line_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_item` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_item` (
  `crm_item_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `crm_brand_id` INT NOT NULL,
  `crm_business_line_id` INT NOT NULL,
  PRIMARY KEY (`crm_item_id`),
  INDEX `fk_crm_item_crm_brand1_idx` (`crm_brand_id` ASC),
  INDEX `fk_crm_item_crm_business_line1_idx` (`crm_business_line_id` ASC),
  CONSTRAINT `fk_crm_item_crm_brand1`
    FOREIGN KEY (`crm_brand_id`)
    REFERENCES `socia`.`crm_brand` (`crm_brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_item_crm_business_line1`
    FOREIGN KEY (`crm_business_line_id`)
    REFERENCES `socia`.`crm_business_line` (`crm_business_line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_quotation_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_quotation_detail` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_quotation_detail` (
  `crm_quotation_detail_id` INT NOT NULL,
  `crm_item_id` INT NOT NULL,
  `unit price` DECIMAL(12,2) NULL,
  `quantity` INT NULL,
  `estimatedShipping` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_quotation_detail_id`),
  INDEX `fk_crm_quotation_detail_crm_item1_idx` (`crm_item_id` ASC),
  CONSTRAINT `fk_crm_quotation_detail_crm_item1`
    FOREIGN KEY (`crm_item_id`)
    REFERENCES `socia`.`crm_item` (`crm_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_quotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_quotation` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_quotation` (
  `crm_quotation_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_address_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  `crm_quotation_detail_id` INT NOT NULL,
  `currency` VARCHAR(45) NULL,
  `exchange_rate` DECIMAL(12,2) NULL,
  PRIMARY KEY (`crm_quotation_id`),
  INDEX `fk_crm_quotation_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_quotation_crm_address1_idx` (`crm_address_id` ASC),
  INDEX `fk_crm_quotation_crm_contact1_idx` (`crm_contact_id` ASC),
  INDEX `fk_crm_quotation_crm_quotation_detail1_idx` (`crm_quotation_detail_id` ASC),
  CONSTRAINT `fk_crm_quotation_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_address1`
    FOREIGN KEY (`crm_address_id`)
    REFERENCES `socia`.`crm_address` (`crm_address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `socia`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_quotation_detail1`
    FOREIGN KEY (`crm_quotation_detail_id`)
    REFERENCES `socia`.`crm_quotation_detail` (`crm_quotation_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_mvs_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_mvs_user` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_mvs_user` (
  `crm_user_id` INT NOT NULL,
  `crm_user_role_id` INT NOT NULL,
  INDEX `fk_crm_mvs_users_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_mvs_users_crm_user_role1_idx` (`crm_user_role_id` ASC),
  CONSTRAINT `fk_crm_mvs_users_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_mvs_users_crm_user_role1`
    FOREIGN KEY (`crm_user_role_id`)
    REFERENCES `socia`.`crm_user_role` (`crm_user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `crm_mvs_user`
--

LOCK TABLES `crm_mvs_user` WRITE;
/*!40000 ALTER TABLE `crm_mvs_user` DISABLE KEYS */;
INSERT INTO `crm_mvs_user` VALUES (1,1),(2,2);
/*!40000 ALTER TABLE `crm_mvs_user` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_mvs_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_mvs_contact` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_mvs_contact` (
  `crm_client_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  INDEX `fk_crm_mvs_contact_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_mvs_contact_crm_contact1_idx` (`crm_contact_id` ASC),
  CONSTRAINT `fk_crm_mvs_contact_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_mvs_contact_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `socia`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `crm_mvs_contact`
--

LOCK TABLES `crm_mvs_contact` WRITE;
/*!40000 ALTER TABLE `crm_mvs_contact` DISABLE KEYS */;
INSERT INTO `crm_mvs_contact` VALUES (1,1),(1,2);
/*!40000 ALTER TABLE `crm_mvs_contact` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_mvs_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_mvs_address` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_mvs_address` (
  `crm_client_id` INT NOT NULL,
  `crm_address_id` INT NOT NULL,
  INDEX `fk_crm_mvs_address_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_mvs_address_crm_address1_idx` (`crm_address_id` ASC),
  CONSTRAINT `fk_crm_mvs_address_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_mvs_address_crm_address1`
    FOREIGN KEY (`crm_address_id`)
    REFERENCES `socia`.`crm_address` (`crm_address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `crm_mvs_address`
--

LOCK TABLES `crm_mvs_address` WRITE;
/*!40000 ALTER TABLE `crm_mvs_address` DISABLE KEYS */;
INSERT INTO `crm_mvs_address` VALUES (1,1),(1,2);
/*!40000 ALTER TABLE `crm_mvs_address` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `socia`.`crm_goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_goal` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_goal` (
  `crm_goal_id` INT NOT NULL,
  `calls` INT NULL,
  `appointments` INT NULL,
  `quotations` INT NULL,
  `calls_scope` DECIMAL(12,2) NULL,
  `appointments_scope` DECIMAL(12,2) NULL,
  `quotations_scope` DECIMAL(12,2) NULL,
  `date_updated` DATETIME NULL,
  `crm_client_id` INT NOT NULL,
  PRIMARY KEY (`crm_goal_id`),
  INDEX `fk_crm_goal_crm_client1_idx` (`crm_client_id` ASC),
  CONSTRAINT `fk_crm_goal_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_registration_requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_registration_requirement` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_registration_requirement` (
  `crm_registration_requirement_id` INT NOT NULL,
  `document_path` VARCHAR(255) NULL,
  `crm_client_id` INT NOT NULL,
  PRIMARY KEY (`crm_registration_requirement_id`),
  INDEX `fk_registration_requirement_crm_client1_idx` (`crm_client_id` ASC),
  CONSTRAINT `fk_registration_requirement_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`company_division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`company_division` ;

CREATE TABLE IF NOT EXISTS `socia`.`company_division` (
  `company_division_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`company_division_id`))
ENGINE = InnoDB;

--
-- Dumping data for table `company_division`
--

LOCK TABLES `company_division` WRITE;
/*!40000 ALTER TABLE `company_division` DISABLE KEYS */;
INSERT INTO `company_division` VALUES (1,'Sistemas'),(2,'Cuentas por pagar'),(3,'Compras');
/*!40000 ALTER TABLE `company_division` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `socia`.`crm_directory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_directory` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_directory` (
  `crm_directory_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `cell_phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `company_division_id` INT NOT NULL,
  `date_of_birth` DATETIME NULL,
  `crm_client_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_directory_id`),
  INDEX `fk_crm_directory_company_division1_idx` (`company_division_id` ASC),
  INDEX `fk_crm_directory_crm_client1_idx` (`crm_client_id` ASC),
  CONSTRAINT `fk_crm_directory_company_division1`
    FOREIGN KEY (`company_division_id`)
    REFERENCES `socia`.`company_division` (`company_division_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_directory_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socia`.`crm_tender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `socia`.`crm_tender` ;

CREATE TABLE IF NOT EXISTS `socia`.`crm_tender` (
  `crm_tender_id` INT NOT NULL,
  `start_up_date` DATETIME NULL,
  `deadline` DATETIME NULL,
  `requirements` VARCHAR(255) NULL,
  `comments` VARCHAR(255) NULL,
  `crm_client_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_business_line_id` INT NOT NULL,
  `crm_directory_decision_maker` INT NOT NULL,
  PRIMARY KEY (`crm_tender_id`),
  INDEX `fk_crm_tender_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_tender_crm_user1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_tender_crm_business_line1_idx` (`crm_business_line_id` ASC),
  INDEX `fk_crm_tender_crm_directory1_idx` (`crm_directory_decision_maker` ASC),
  CONSTRAINT `fk_crm_tender_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `socia`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_tender_crm_user1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `socia`.`crm_user` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_tender_crm_business_line1`
    FOREIGN KEY (`crm_business_line_id`)
    REFERENCES `socia`.`crm_business_line` (`crm_business_line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_tender_crm_directory1`
    FOREIGN KEY (`crm_directory_decision_maker`)
    REFERENCES `socia`.`crm_directory` (`crm_directory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
