-- MySQL Script generated by MySQL Workbench
-- 10/01/16 13:06:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `socia` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socia` DEFAULT CHARACTER SET utf8 ;
USE `socia` ;

-- -----------------------------------------------------
-- Table `mydb`.`crm_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_users` (
  `crm_user_id` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dateCreated` DATETIME NULL,
  PRIMARY KEY (`crm_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_user_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_user_role` (
  `crm_user_role_id` INT NOT NULL,
  `roleDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_user_role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_address` (
  `crm_address_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `ext_num` VARCHAR(45) NULL,
  `int_num` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  PRIMARY KEY (`crm_address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_contact` (
  `crm_contact_id` INT NOT NULL,
  `contact_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`crm_contact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_client` (
  `crm_client_id` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `crm_address_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  `crm_bdm_id` INT NOT NULL,
  PRIMARY KEY (`crm_client_id`),
  INDEX `fk_crm_client_crm_address1_idx` (`crm_address_id` ASC),
  INDEX `fk_crm_client_crm_contact1_idx` (`crm_contact_id` ASC),
  INDEX `fk_crm_client_crm_users1_idx` (`crm_bdm_id` ASC),
  CONSTRAINT `fk_crm_client_crm_address1`
    FOREIGN KEY (`crm_address_id`)
    REFERENCES `mydb`.`crm_address` (`crm_address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_client_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `mydb`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_client_crm_users1`
    FOREIGN KEY (`crm_bdm_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_call` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_call` (
  `crm_call_id` INT NOT NULL,
  `comments` VARCHAR(255) NULL,
  `crm_client_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  PRIMARY KEY (`crm_call_id`),
  INDEX `fk_crm_call_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_call_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_call_crm_contact1_idx` (`crm_contact_id` ASC),
  CONSTRAINT `fk_crm_call_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `mydb`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_call_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_call_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `mydb`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_consecutives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_consecutives` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_consecutives` (
  `crm_client_id` INT NOT NULL,
  `consecutive` INT NULL,
  PRIMARY KEY (`crm_client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_appointments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_appointments` (
  `crm_appointments_id` INT NOT NULL,
  `date` DATETIME NULL,
  `crm_client_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_bdm_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  PRIMARY KEY (`crm_appointments_id`),
  INDEX `fk_crm_appointments_crm_client1_idx` (`crm_client_id` ASC),
  INDEX `fk_crm_appointments_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_appointments_crm_users2_idx` (`crm_bdm_id` ASC),
  INDEX `fk_crm_appointments_crm_contact1_idx` (`crm_contact_id` ASC),
  CONSTRAINT `fk_crm_appointments_crm_client1`
    FOREIGN KEY (`crm_client_id`)
    REFERENCES `mydb`.`crm_client` (`crm_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointments_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointments_crm_users2`
    FOREIGN KEY (`crm_bdm_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_appointments_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `mydb`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_item` (
  `crm_item_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`crm_item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_quotation_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_quotation_detail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_quotation_detail` (
  `crm_quotation_detail_id` INT NOT NULL,
  `crm_item_id` INT NOT NULL,
  `unit price` DECIMAL(12,2) NULL,
  `quantity` INT NULL,
  `delivery_date` DATETIME NULL,
  PRIMARY KEY (`crm_quotation_detail_id`),
  INDEX `fk_crm_quotation_detail_crm_item1_idx` (`crm_item_id` ASC),
  CONSTRAINT `fk_crm_quotation_detail_crm_item1`
    FOREIGN KEY (`crm_item_id`)
    REFERENCES `mydb`.`crm_item` (`crm_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_quotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_quotation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_quotation` (
  `crm_quotation_id` INT NOT NULL,
  `crm_user_id` INT NOT NULL,
  `crm_address_id` INT NOT NULL,
  `crm_contact_id` INT NOT NULL,
  `crm_quotation_detail_id` INT NOT NULL,
  `currency` VARCHAR(45) NULL,
  `exchange_rate` DECIMAL(12,2) NULL,
  PRIMARY KEY (`crm_quotation_id`),
  INDEX `fk_crm_quotation_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_quotation_crm_address1_idx` (`crm_address_id` ASC),
  INDEX `fk_crm_quotation_crm_contact1_idx` (`crm_contact_id` ASC),
  INDEX `fk_crm_quotation_crm_quotation_detail1_idx` (`crm_quotation_detail_id` ASC),
  CONSTRAINT `fk_crm_quotation_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_address1`
    FOREIGN KEY (`crm_address_id`)
    REFERENCES `mydb`.`crm_address` (`crm_address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_contact1`
    FOREIGN KEY (`crm_contact_id`)
    REFERENCES `mydb`.`crm_contact` (`crm_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_quotation_crm_quotation_detail1`
    FOREIGN KEY (`crm_quotation_detail_id`)
    REFERENCES `mydb`.`crm_quotation_detail` (`crm_quotation_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`business_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`business_line` ;

CREATE TABLE IF NOT EXISTS `mydb`.`business_line` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crm_mvs_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`crm_mvs_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`crm_mvs_users` (
  `crm_user_id` INT NOT NULL,
  `crm_user_role_id` INT NOT NULL,
  INDEX `fk_crm_mvs_users_crm_users1_idx` (`crm_user_id` ASC),
  INDEX `fk_crm_mvs_users_crm_user_role1_idx` (`crm_user_role_id` ASC),
  CONSTRAINT `fk_crm_mvs_users_crm_users1`
    FOREIGN KEY (`crm_user_id`)
    REFERENCES `mydb`.`crm_users` (`crm_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_mvs_users_crm_user_role1`
    FOREIGN KEY (`crm_user_role_id`)
    REFERENCES `mydb`.`crm_user_role` (`crm_user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
